server:
  port: 7002
spring:
  application:
    name: gateway-service
  redis:
    host: 127.0.0.1
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka
    registry-fetch-interval-seconds: 5 #修改拉取周期5s
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
    lease-renewal-interval-in-seconds: 5 #修改心跳为5s
    lease-expiration-duration-in-seconds: 15 #修改过期时间



